[package]
name = "lavinmq-quickcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
quickcheck = "1"
lapin = "2"

[dev-dependencies]
quickcheck_macros = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }
futures-lite = "2"
ureq = { version = "3.4.2", default-features = false }
serde_json = { version = "1.0.151", features = ["float_roundtrip"] }
rumqttc = { version = "0.25.1", default-features = false }
